---
- name: Extra vars vault
  connection: local
  hosts: localhost
  gather_facts: no
  no_log: true

  # note that we don't have a vars_files section here!

  tasks:
    - name: print out encrypted vars
      ansible.builtin.debug:
        msg: "{{ imscloud }}"

